# Generated by Django 5.2 on 2025-04-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('name',), 'verbose_name_plural': 'Items'},
        ),
    ]
